config/routes.rb
Rails.application.routes.draw do
  resources :cadastro_externos
  resources :produto_imagems
  resources :marca_nome_alternativos
  resources :usuario_avalia_marcas
  resources :usuario_avalia_produtos
  resources :usuario_busca_marcas
  resources :usuario_busca_produtos
  resources :usuario_busca_componentes
  resources :produto_possui_componentes
  resources :componente_nome_alternativos
  resources :produto_nome_alternativos
  resources :componentes
  resources :produtos
  resources :marcas
  
  #devise_for :usuarios
  devise_for :usuarios, controllers: { omniauth_callbacks: 'usuarios/omniauth' }

  root 'inicio#index'
  get "dev" => "dev#index"
  get "dev/remover/:id", to: "dev#remover", as: "remover_dev"
  get "dev/adicionar/", to: "dev#adicionar", as: "adicionar_dev"
  
  get "inicio" => "inicio#index"
  
  get "busca" => "busca#buscar"
  get "busca_ocr" => "busca#buscar_ocr"
  get "busca_cod" => "busca#buscar_cod"
  
  get "produto_imagems/new/:id" => "produto_imagems#new" 
  get "perfil" => "perfil#index"
  get "historico" => "historico#index"
  
  get "equipeone" => "welcome#equipeone"
  get "ajuda" => "welcome#ajuda"

end

app/models/marca.rb
class Marca < ApplicationRecord
    def valid
        errors.add(:nome, "não pode ficar em branco") if nome == "" or nome.nil?
        errors.add(:descricao, "não pode ficar em branco") if descricao == "" or descricao.nil?
        errors.add(:class_vegan, "não pode ficar em branco") if class_vegan.nil?
        errors.add(:justificativa, "não pode ficar em branco") if justificativa == "" or justificativa.nil?
    end
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  #before_action :authenticate_usuario!
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
    # Adicionar no histórico de pesquisa
    if usuario_signed_in?
      consulta = UsuarioBuscaMarca.where("usuario_id = " + current_usuario.id.to_s + " AND " + "marca_id = " + @marca.id.to_s)
      if consulta.size > 0
        consulta[0].dt_busca = Time.now.to_s
        consulta[0].save
      else
        UsuarioBuscaMarca.create(usuario_id: current_usuario.id, marca_id: @marca.id, dt_busca: Time.now.to_s)
      end
    end
    
  end

  # GET /marcas/new
  def new
    authorize! :menage, :all
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
    authorize! :menage, :all
  end

  # POST /marcas
  # POST /marcas.json
  def create
    authorize! :menage, :all
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca criada com sucesso.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    authorize! :menage, :all
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca atualizada com suceso.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    authorize! :menage, :all
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:nome, :descricao, :class_vegan, :justificativa)
    end
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/views/marcas/_form.html.erb
<%= form_with(model: marca, local: true) do |form| %>
  <% if marca.errors.any? %>
    <div id="error_explanation">
      <h2 class = "color-font"><%= pluralize(marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
      <% marca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :nome, class: "form-control", placeholder: "Nome da Marca"%>
  </div>

  <div class="form-group">
    <%= form.text_area :descricao, class: "form-control", placeholder: "Descrição"%>
  </div>

  <div class="form-group">
    <%= form.number_field :class_vegan, class: "form-control", placeholder: "É vegano?"%>
  </div>

  <div class="form-group">
    <%= form.text_area :justificativa, class: "form-control", placeholder: "Por quê?"%>
  </div>

  <div class="actions">
    <center><%= form.submit class: "btn btn-primary-evegano" %></center>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<div class = "container-box">
    <h2 class = "color-font"><center>Editar Marca</center></h2>

    <%= render 'form', marca: @marca %>

    <%= link_to 'Mostrar', @marca %> |
    <%= link_to 'Voltar', marcas_path %>

</div>

app/views/marcas/index.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Marcas</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Class vegan</th>
      <th>Justificativa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.id%></td>
        <td><%= marca.nome %></td>
        <td><%= marca.descricao %></td>
        <td><%= marca.class_vegan %></td>
        <td><%= marca.justificativa %></td>
        <td><%= link_to 'Show', marca %></td>
        <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
        <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Marca', new_marca_path %>

app/views/marcas/new.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<div class = "container-box">
    <h2 class = "color-font"><center>Nova Marca</center></h2>

    <%= render 'form', marca: @marca %>
    
    <%= link_to 'Voltar', marcas_path %>

</div>

app/views/marcas/show.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<%= render "shared/notice" %>
  
<div class = "container-box">
  <%= render "shared/pmc_basic_infos", pmc: @marca%>
  <hr>
  
  <p>
    <strong>Descrição:</strong></br>
    <%= @marca.descricao %>
  </p>
  
  <p>
    <strong>Justificativa da Classificação:</strong></br>
    <%= @marca.justificativa %>
  </p>
  
  <% if usuario_signed_in? and current_usuario.dev then%>
    <%= link_to 'Editar', edit_marca_path(@marca) %> |
  <% end %>
  
  <%= link_to 'Voltar', :back %>
</div>