config/routes.rb
Rails.application.routes.draw do
  resources :cadastro_externos
  resources :produto_imagems
  resources :marca_nome_alternativos
  resources :usuario_avalia_marcas
  resources :usuario_avalia_produtos
  resources :usuario_busca_marcas
  resources :usuario_busca_produtos
  resources :usuario_busca_componentes
  resources :produto_possui_componentes
  resources :componente_nome_alternativos
  resources :produto_nome_alternativos
  resources :componentes
  resources :produtos
  resources :marcas
  
  #devise_for :usuarios
  devise_for :usuarios, controllers: { omniauth_callbacks: 'usuarios/omniauth' }

  root 'inicio#index'
  get "dev" => "dev#index"
  get "dev/remover/:id", to: "dev#remover", as: "remover_dev"
  get "dev/adicionar/", to: "dev#adicionar", as: "adicionar_dev"
  
  get "inicio" => "inicio#index"
  
  get "busca" => "busca#buscar"
  get "busca_ocr" => "busca#buscar_ocr"
  get "busca_cod" => "busca#buscar_cod"
  
  get "produto_imagems/new/:id" => "produto_imagems#new" 
  get "perfil" => "perfil#index"
  get "historico" => "historico#index"
  
  get "equipeone" => "welcome#equipeone"
  get "ajuda" => "welcome#ajuda"

end

app/controllers/busca_controller.rb
class BuscaController < ApplicationController
    #before_action :authenticate_usuario!
    
    def index
    end
    
    def show
    end
    
    def buscar_ocr
        @ocr = params[:ocr]
        produtos = Produto.all
        ocr = @ocr.split(" ")
        
        menor_palavra = [ocr[0], 10000]
        ocr.each do |palavra|
            produtos.each do |produto|
                distancia = leven_quebrar(palavra, produto.nome)
                if distancia < menor_palavra[1]
                    menor_palavra = [palavra, distancia]
                end
            end
        end
        
        if menor_palavra[1] < 2
            redirect_to controller: "busca", action: 'buscar', texto: menor_palavra[0]
            
        else
            flash[:notice] = "Não conseguimos encontrar com seu rótulo. :("
            redirect_to inicio_path
        end
        
        
    end

    def buscar_cod
        cod = params[:cod]
        produtos = Produto.where("cod_barras = '"+cod+"'")
        
        if produtos.size > 0
            redirect_to produtos[0]
        else
            flash[:notice] = "Não achamos nenhum produto com esse código de barras."
            redirect_to inicio_path
        end
    end
    
    def buscar
        @nome_busca = params[:texto]
        @proximos = leven(@nome_busca)
        
        if busca_vazia
            redirect_to inicio_path
            return
        end
        
        @candidatos_produtos = Produto.where "lower(nome) like lower(?)", "%#{@nome_busca}%"
        @candidatos_marcas = Marca.where "lower(nome) like lower(?)", "%#{@nome_busca}%"
        @candidatos_componentes = Componente.where "lower(nome) like lower(?)", "%#{@nome_busca}%"
        
        if @candidatos_produtos.size == 1 and (@candidatos_marcas.size == 0) and (@candidatos_componentes.size == 0)
            redirect_to(produtos_url+"/"+@candidatos_produtos[0].id.to_s)
            
        elsif @candidatos_marcas.size == 1 and (@candidatos_produtos.size == 0) and (@candidatos_componentes.size == 0)
            redirect_to(marcas_url+"/"+@candidatos_marcas[0].id.to_s)
            
        elsif @candidatos_componentes.size == 1 and (@candidatos_marcas.size == 0) and (@candidatos_produtos.size == 0)
            redirect_to(componentes_url+"/"+@candidatos_componentes[0].id.to_s)
        else
            render :index
        end
    end
    
    private 
    
    def busca_vazia
        if @nome_busca == ""
            return true
        else
            return false
        end
    end
    
    # Essa função pega todos elementos do banco e compara com o termo buscado numa
    # distância de Levenshtein maior que 0 (mesmo termo), e menor que 3.
    def leven(busca)
        proximos = Array.new
        objetos = Array.new
        
        objetos = objetos + Produto.all + Marca.all + Componente.all
        objetos.each do |obj|
            distancia = leven_quebrar(busca,obj.nome)
            if distancia > 0 and distancia < 3
                proximos << obj
            end
        end
        
        return proximos
    end
    
    # Essa função faz o valor "distância" da função anterior ser comparado por cada
    # palavra dentro dos termo buscado, e não o termo buscado completo.
    def leven_quebrar(busca, termo)
        menor = Levenshtein.distance(termo.downcase,busca.to_s.downcase)
        termo = termo.split(" ")
        
        termo.each do |palavra|
            if Levenshtein.distance(palavra.downcase,busca.to_s.downcase) < menor
                menor = Levenshtein.distance(palavra.downcase,busca.to_s.downcase)
            end
        end
        
        return menor
    end
end

app/helpers/busca_helper.rb
module BuscaHelper
end

app/views/busca/_caso_multiplo.html.erb
<div class = "container-box">
    <h3> Legal! Achamos tudo isso com "<%= @nome_busca %>"!</h3>
    <br/>
    
    <% if @candidatos_produtos.size >= 1 %>
        <h4>Produtos</h4>
        <%= render "cm_produtos" %>
    <% end %>
    
    <% if @candidatos_marcas.size >= 1 %>
        <h4>Marcas</h4>
        <%= render "cm_marcas" %>
    <% end %>
    
     <% if @candidatos_componentes.size >= 1 %>
        <h4>Componentes</h4>
        <%= render "cm_componentes"%>
    <% end %>
    
</div>

app/views/busca/_caso_ruim.html.erb
<div class = "container-box">
    <h3> Ainda nada? Que tal ajudar o <strong>É vegano?</strong> cadastrando "<%=@nome_busca%>"? </h3>
    
    <small>Insira as informações que você tiver sobre o que você estava buscando. 
    Não precisa preencher tudo, basta complementar o que você souber responder.</small>
    
    <br/> <br/> 
    <%= render "/cadastro_externos/form", cadastro_externo: CadastroExterno.new, nome_busca: @nome_busca%>
</div>

app/views/busca/_cm_componentes.html.erb
<div class = "scrolled">
    <div class="table-responsive-sm">
        <table class = "table table-striped">
                <thead class = "thead-light">
                   <tr>
                    <th scope="col">Nome</th>
                    </tr> 
                </thead>
                <tbody>
                    <% @candidatos_componentes.each do |comp| %>
                        <tr>
                            <td><%= link_to comp.nome.to_s, componentes_path(comp)%></td>
                        </tr>
                    <% end %>
                </tbody>
        </table>
    </div>
</div>

app/views/busca/_cm_marcas.html.erb
<div class = "scrolled">
    <div class="table-responsive-sm">
        <table class = "table table-striped">
                <thead class = "thead-light">
                   <tr>
                    <th scope="col">Nome</th>
                    </tr> 
                </thead>
                <tbody>
                    <% @candidatos_marcas.each do |marca| %>
                        <tr>
                            <td><%= link_to marca.nome.to_s, marca_path(marca)%></td>
                        </tr>
                    <% end %>
                </tbody>
        </table>
    </div>
</div>

app/views/busca/_cm_produtos.html.erb
<div class = "scrolled">
    <div class="table-responsive-sm">
        <table class = "table table-striped">
                <thead class = "thead-light">
                   <tr>
                    <th scope="col">Nome</th>
                    </tr> 
                </thead>
                <tbody>
                    <% @candidatos_produtos.each do |produto| %>
                        <tr>
                            <td><%= link_to produto.nome.to_s, produto_path(produto)%></td>
                        </tr>
                    <% end %>
                </tbody>
        </table>
    </div>
</div>

app/views/busca/_proximos.html.erb
<div class = "container-box">
    <h3> Não encontrou ainda? Será que você não quis dizer? </h3>
    <br/>

    <div class = "scrolled">
        <div class="table-responsive-sm">
            <table class = "table table-striped table-bordered table-sm">
                
                <thead class = "thead-light">
                    <th scope = "col">Tipo</th>
                    <th scope = "col">Nome</th>
                </thead>
                <tbody>
                    <% @proximos.each do |pro|%>
                    <tr scope = "row">
                        <td><%= pro.class %></td>
                        <% if pro.class() == Produto %>
                            <td><%= link_to pro.nome, produto_path(pro.id) %></td>
                        <% elsif pro.class() == Marca %>
                            <td><%= link_to pro.nome, marca_path(pro.id) %></td>
                        <% else %>
                            <td><%= link_to pro.nome, componente_path(pro.id) %></td>
                        <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/busca/index.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<% if @candidatos_produtos.size >= 1  or @candidatos_marcas.size >= 1 or @candidatos_componentes.size >= 1%>
    <%= render "caso_multiplo" %>
    <br />
<% end %>


<% if @proximos.size > 0 %>
    <%= render "proximos" %>
    <br />
<% end %>

<%= render "caso_ruim" %>
<br />