config/routes.rb
Rails.application.routes.draw do
  resources :cadastro_externos
  resources :produto_imagems
  resources :marca_nome_alternativos
  resources :usuario_avalia_marcas
  resources :usuario_avalia_produtos
  resources :usuario_busca_marcas
  resources :usuario_busca_produtos
  resources :usuario_busca_componentes
  resources :produto_possui_componentes
  resources :componente_nome_alternativos
  resources :produto_nome_alternativos
  resources :componentes
  resources :produtos
  resources :marcas
  
  #devise_for :usuarios
  devise_for :usuarios, controllers: { omniauth_callbacks: 'usuarios/omniauth' }

  root 'inicio#index'
  get "dev" => "dev#index"
  get "dev/remover/:id", to: "dev#remover", as: "remover_dev"
  get "dev/adicionar/", to: "dev#adicionar", as: "adicionar_dev"
  
  get "inicio" => "inicio#index"
  
  get "busca" => "busca#buscar"
  get "busca_ocr" => "busca#buscar_ocr"
  get "busca_cod" => "busca#buscar_cod"
  
  get "produto_imagems/new/:id" => "produto_imagems#new" 
  get "perfil" => "perfil#index"
  get "historico" => "historico#index"
  
  get "equipeone" => "welcome#equipeone"
  get "ajuda" => "welcome#ajuda"

end

app/models/produto.rb
class Produto < ApplicationRecord
    belongs_to :marca
    
    def valid
        errors.add(:nome, "não pode ficar em branco") if nome == "" or nome.nil?
        errors.add(:marca_id, "não pode ficar em branco") if marca_id.nil?
        errors.add(:descricao, "não pode ficar em branco") if descricao == "" or descricao.nil?
        errors.add(:class_vegan, "não pode ficar em branco") if class_vegan.nil?
        errors.add(:justificativa, "não pode ficar em branco") if justificativa == "" or justificativa.nil?
    end
    
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  #before_action :authenticate_usuario!
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    authorize! :menage, :all
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    # Para adiciona no histórico du usuário
    if usuario_signed_in?
      consulta = UsuarioBuscaProduto.where("usuario_id = " + current_usuario.id.to_s + " AND " + "produto_id = " + @produto.id.to_s)
      if consulta.size > 0
        consulta[0].dt_busca = Time.now.to_s
        consulta[0].save
      else
        UsuarioBuscaProduto.create(usuario_id: current_usuario.id, produto_id: @produto.id, dt_busca: Time.now.to_s)
      end
    end
    
    # Para povoar a lista de componentes
    comps_produto = ProdutoPossuiComponente.where("produto_id = " + @produto.id.to_s)
    @comps_produto = Array.new
    
    comps_produto.each do |comp|
      @comps_produto << Componente.where("id = " + comp.componente_id.to_s)[0]
    end
    
  end

  # GET /produtos/new
  def new
    authorize! :menage, :all
    @ipp = params[:id]
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
    authorize! :menage, :all
  end

  # POST /produtos
  # POST /produtos.json
  def create
    authorize! :menage, :all
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    authorize! :menage, :all
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    authorize! :menage, :all
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:cod_barras, :nome, :marca_id, :descricao, :class_vegan, :justificativa)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2 class = "color-font"><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :cod_barras, class: "form-control", placeholder: "Código de Barras"%>
  </div>

  <div class="form-group">
    <%= form.text_field :nome, class: "form-control", placeholder: "Nome" %>
  </div>

  <div class="form-group">
    <%= form.text_field :marca_id, class: "form-control", placeholder: "Marca" %>
  </div>

  <div class="form-group">
    <%= form.text_area :descricao, class: "form-control", placeholder: "Descrição" %>
  </div>


  <div class="form-group">
    <%= form.number_field :class_vegan, class: "form-control", placeholder: "É vegano?" %>
  </div>

  <div class="form-group">
    <%= form.text_area :justificativa, class: "form-control", placeholder: "Por quê?" %>
  </div>


  <div class="actions">
    <center><%= form.submit class: "btn btn-primary-evegano"  %></center>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<div class = "container-box">
    <h2 class = "color-font"><center>Editar Produto</center></h2>

    <%= render 'form', produto: @produto %>
    
    <%= link_to 'Mostrar', @produto %> |
    <%= link_to 'Voltar', produtos_path %>

</div>

app/views/produtos/index.html.erb
<% # encoding: utf-8 %>
<meta charset="UTF-8"> 

<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>
  
<%= render "shared/notice" %>

<h1>Produtos</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Cod barras</th>
      <th>Nome</th>
      <th>Marca</th>
      <th>Descrição</th>
      <th>É vegano?</th>
      <th>Justificativa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.id %></td>
        <td><%= produto.cod_barras %></td>
        <td><%= produto.nome %></td>
        <td><%= produto.marca.nome %></td>
        <td><%= produto.descricao %></td>
        <td><%= produto.class_vegan %></td>
        <td><%= produto.justificativa %></td>
        <td><%= link_to 'Mostrar', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Deletar', produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path %>

app/views/produtos/new.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<div class = "container-box">
    <h2 class = "color-font"><center>Novo produto</center></h2>
    
    <%= render 'form', produto: @produto%>
    
    <%= link_to 'Voltar', produtos_path %>
</div>

app/views/produtos/show.html.erb
<%= content_for :nav do%>
  <%= render "layouts/navbar" %>
<% end %>

<%= render "shared/notice" %>

<div class = "container-box">
  
  <%= render "shared/pmc_basic_infos", pmc: @produto%>
  <hr>

  <p>
    <strong>Marca:</strong>
    <%= link_to @produto.marca.nome, marca_path(@produto.marca) %>
  </p>
  
  
  
  <p>
    <strong>Descrição:</strong> </br>
    <%= @produto.descricao %>
  </p>
  
  <p>
    <strong>Componentes:</strong> </br>
    <% @comps_produto.each do |comp| %>
      <%= link_to comp.nome, componente_path(comp) %>; 
    <% end %>
  </p>
  
  <p>
    <strong>Justificativa da Classificação:</strong> </br>
    <%= @produto.justificativa %>
  </p>
  
  
  <% if usuario_signed_in? and current_usuario.dev then%>
    <%= link_to 'Editar', edit_produto_path(@produto) %>
  <% end %>
  
  <%= link_to 'Voltar', :back %>

</div>