config/routes.rb
Rails.application.routes.draw do
  resources :cadastro_externos
  resources :produto_imagems
  resources :marca_nome_alternativos
  resources :usuario_avalia_marcas
  resources :usuario_avalia_produtos
  resources :usuario_busca_marcas
  resources :usuario_busca_produtos
  resources :usuario_busca_componentes
  resources :produto_possui_componentes
  resources :componente_nome_alternativos
  resources :produto_nome_alternativos
  resources :componentes
  resources :produtos
  resources :marcas
  
  #devise_for :usuarios
  devise_for :usuarios, controllers: { omniauth_callbacks: 'usuarios/omniauth' }

  root 'inicio#index'
  get "dev" => "dev#index"
  get "dev/remover/:id", to: "dev#remover", as: "remover_dev"
  get "dev/adicionar/", to: "dev#adicionar", as: "adicionar_dev"
  
  get "inicio" => "inicio#index"
  
  get "busca" => "busca#buscar"
  get "busca_ocr" => "busca#buscar_ocr"
  get "busca_cod" => "busca#buscar_cod"
  
  get "produto_imagems/new/:id" => "produto_imagems#new" 
  get "perfil" => "perfil#index"
  get "historico" => "historico#index"
  
  get "equipeone" => "welcome#equipeone"
  get "ajuda" => "welcome#ajuda"

end

app/models/marca_nome_alternativo.rb
class MarcaNomeAlternativo < ApplicationRecord
  belongs_to :marca
end

app/controllers/marca_nome_alternativos_controller.rb
class MarcaNomeAlternativosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_marca_nome_alternativo, only: [:show, :edit, :update, :destroy]

  # GET /marca_nome_alternativos
  # GET /marca_nome_alternativos.json
  def index
    authorize! :menage, :all
    @marca_nome_alternativos = MarcaNomeAlternativo.all
  end

  # GET /marca_nome_alternativos/1
  # GET /marca_nome_alternativos/1.json
  def show
    authorize! :menage, :all
  end

  # GET /marca_nome_alternativos/new
  def new
    authorize! :menage, :all
    @marca_nome_alternativo = MarcaNomeAlternativo.new
  end

  # GET /marca_nome_alternativos/1/edit
  def edit
    authorize! :menage, :all
  end

  # POST /marca_nome_alternativos
  # POST /marca_nome_alternativos.json
  def create
    authorize! :menage, :all
    @marca_nome_alternativo = MarcaNomeAlternativo.new(marca_nome_alternativo_params)

    respond_to do |format|
      if @marca_nome_alternativo.save
        format.html { redirect_to @marca_nome_alternativo, notice: 'Marca nome alternativo was successfully created.' }
        format.json { render :show, status: :created, location: @marca_nome_alternativo }
      else
        format.html { render :new }
        format.json { render json: @marca_nome_alternativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marca_nome_alternativos/1
  # PATCH/PUT /marca_nome_alternativos/1.json
  def update
    authorize! :menage, :all
    respond_to do |format|
      if @marca_nome_alternativo.update(marca_nome_alternativo_params)
        format.html { redirect_to @marca_nome_alternativo, notice: 'Marca nome alternativo was successfully updated.' }
        format.json { render :show, status: :ok, location: @marca_nome_alternativo }
      else
        format.html { render :edit }
        format.json { render json: @marca_nome_alternativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marca_nome_alternativos/1
  # DELETE /marca_nome_alternativos/1.json
  def destroy
    authorize! :menage, :all
    @marca_nome_alternativo.destroy
    respond_to do |format|
      format.html { redirect_to marca_nome_alternativos_url, notice: 'Marca nome alternativo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca_nome_alternativo
      @marca_nome_alternativo = MarcaNomeAlternativo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_nome_alternativo_params
      params.require(:marca_nome_alternativo).permit(:marca_id, :nome)
    end
end

app/helpers/marca_nome_alternativos_helper.rb
module MarcaNomeAlternativosHelper
end

app/views/marca_nome_alternativos/_form.html.erb
<%= form_with(model: marca_nome_alternativo, local: true) do |form| %>
  <% if marca_nome_alternativo.errors.any? %>
    <div id="error_explanation">
      <h2 class = "color-font"><%= pluralize(marca_nome_alternativo.errors.count, "error") %> prohibited this marca_nome_alternativo from being saved:</h2>

      <ul>
      <% marca_nome_alternativo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marca_id %>
    <%= form.text_field :marca_id %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marca_nome_alternativos/edit.html.erb
<h1>Editing Marca Nome Alternativo</h1>

<%= render 'form', marca_nome_alternativo: @marca_nome_alternativo %>

<%= link_to 'Show', @marca_nome_alternativo %> |
<%= link_to 'Back', marca_nome_alternativos_path %>

app/views/marca_nome_alternativos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marca Nome Alternativos</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Marca</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marca_nome_alternativos.each do |marca_nome_alternativo| %>
      <tr>
        <td><%= marca_nome_alternativo.marca %></td>
        <td><%= marca_nome_alternativo.nome %></td>
        <td><%= link_to 'Show', marca_nome_alternativo %></td>
        <td><%= link_to 'Edit', edit_marca_nome_alternativo_path(marca_nome_alternativo) %></td>
        <td><%= link_to 'Destroy', marca_nome_alternativo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marca Nome Alternativo', new_marca_nome_alternativo_path %>

app/views/marca_nome_alternativos/new.html.erb
<h1>New Marca Nome Alternativo</h1>

<%= render 'form', marca_nome_alternativo: @marca_nome_alternativo %>

<%= link_to 'Back', marca_nome_alternativos_path %>

app/views/marca_nome_alternativos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @marca_nome_alternativo.marca %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @marca_nome_alternativo.nome %>
</p>

<%= link_to 'Edit', edit_marca_nome_alternativo_path(@marca_nome_alternativo) %> |
<%= link_to 'Back', marca_nome_alternativos_path %>